// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetPath(arg1:string):Promise<string>;

export function GetRoles():Promise<Array<string>>;

export function SelectPath():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function SyncRoleData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:boolean):Promise<string>;
