// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPath(arg1) {
  return window['go']['service']['Role']['GetPath'](arg1);
}

export function GetRoles() {
  return window['go']['service']['Role']['GetRoles']();
}

export function SelectPath() {
  return window['go']['service']['Role']['SelectPath']();
}

export function Startup(arg1) {
  return window['go']['service']['Role']['Startup'](arg1);
}

export function SyncRoleData(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['service']['Role']['SyncRoleData'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}
